pipeline:
  name: echo
  identifier: echo
  projectIdentifier: test_1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: echo
        identifier: echo
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo hi
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
